### PR TITLE
Added custom button support for Rich Presence

### PR DESCRIPTION
**Pull request by Killarexe**
Adding custom button support for rich presence and updated/fixed the README.md.
If you want to test by yourself just add `.setButton1("Some text", "https://ururl.com")` to the builder.

### CODE REVIEW

**Comment by rickmartensnl** [comment]
Any update on this?

**Comment by Killarexe** [comment]
Well this pull just adds a button support, update packages and adds a better README that's it. But it's seems like the owner of this repo isn't insterested by this feature...

**Comment by Killarexe** [comment]
> Any update on this?

Well this pull just adds a button support, update packages and adds a better README that's it. But it's seems like the owner of this repo isn't insterested by this feature...

**Comment by Killarexe** [comment]
Well, after almost 1 year. It seems that the creator of the repo isn't interested to maintain this. So I close this pull request. 

And if you are interested in this feature I recommend using [CDAGaming's fork](https://github.com/CDAGaming/DiscordIPC/tree/publish)! Witch is a great fork still maintained nowadays by him.

**Pull request closed without merging**
